INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CREACION) VALUES ('Panasonic', 800, NOW());
INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CREACION) VALUES ('Sony', 700, NOW());
INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CREACION) VALUES ('Apple', 1000, NOW());
INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CREACION) VALUES ('Sony Notebook', 1000, NOW());
INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CREACION) VALUES ('Hewlett', 500, NOW());
INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CREACION) VALUES ('Bianchi', 600, NOW());
INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CREACION) VALUES ('Nike', 100, NOW());
INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CREACION) VALUES ('Xiaomi Mi 8', 250, NOW());
INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CREACION) VALUES ('Reebok', 300, NOW());